version: '3'

services:
  # database:
  #   image: postgres:${POSTGRES_VERSION:-13}-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB:-app}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #   volumes:
  #     - ./var/docker/db/data:/var/lib/postgresql/data:rw
  # redis:
  #   image: redis/redis-stack-server:6.2.2-v1
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./var/docker/redis/data:/data:rw
  #   environment:
  #     REDIS_ARGS: --requirepass ${REDIS_PASSWORD:-redis-stack-password}
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/app
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
  nginx:
    image: nginx:alpine
    ports:
      - "3002:80"
    volumes:
      - ./:/app
      - ./var/log/nginx:/var/log/nginx
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    working_dir: /app
